In [1]:
import sys 
sys.path.append("..") 

import numpy as np
import pandas as pd
from SWMM import SWMM_ENV
from DQN import Buffer
from DQN import DQN as DQN
import tensorflow as tf
import matplotlib.pyplot as plt
from joblib import Parallel, delayed
import os

In [2]:
np.load('time.npy',allow_pickle=True)

array([ 36.0920561,  71.2160077, 704.2051124])

In [5]:
agent_params={
    'state_dim':18,
    'action_dim':pd.read_csv(os.path.dirname(os.getcwd())+'/SWMM/action_table.csv').values[:,1:].shape[0],

    'encoding_layer':[50,50],
    'value_layer':[50,50],
    'advantage_layer':[50,50],
    'num_rain':50,


    'train_iterations':10,
    'training_step':500,
    'gamma':0.01,
    'epsilon':0.1,
    'ep_min':1e-50,
    'ep_decay':0.9,
    'learning_rate':0.001,

    'action_table':pd.read_csv(os.path.dirname(os.getcwd())+'/SWMM/action_table.csv').values[:,1:],
}

In [17]:
agent_params['action_table']

array([[1.    , 0.2366, 0.6508, 0.3523, 1.    , 0.4303],
       [1.    , 0.2366, 0.6508, 0.3523, 1.    , 0.1687],
       [1.    , 0.2366, 0.6508, 0.1894, 1.    , 0.4303],
       [1.    , 0.2366, 0.6508, 0.1894, 1.    , 0.1687],
       [1.    , 0.2366, 0.3159, 0.3523, 1.    , 0.4303],
       [1.    , 0.2366, 0.3159, 0.3523, 1.    , 0.1687],
       [1.    , 0.2366, 0.3159, 0.1894, 1.    , 0.4303],
       [1.    , 0.2366, 0.3159, 0.1894, 1.    , 0.1687],
       [1.    , 0.1075, 0.6508, 0.3523, 1.    , 0.4303],
       [1.    , 0.1075, 0.6508, 0.3523, 1.    , 0.1687],
       [1.    , 0.1075, 0.6508, 0.1894, 1.    , 0.4303],
       [1.    , 0.1075, 0.6508, 0.1894, 1.    , 0.1687],
       [1.    , 0.1075, 0.3159, 0.3523, 1.    , 0.4303],
       [1.    , 0.1075, 0.3159, 0.3523, 1.    , 0.1687],
       [1.    , 0.1075, 0.3159, 0.1894, 1.    , 0.4303],
       [1.    , 0.1075, 0.3159, 0.1894, 1.    , 0.1687]])

In [18]:
for it in range(agent_params['action_table'].shape[0]):
    if (agent_params['action_table'][it] == np.array([1.    , 0.1075, 0.6508, 0.3523, 1.    , 0.1687])).all():
        print(it)

9


In [19]:
optdata = np.load(os.path.abspath(os.path.join(os.getcwd(), os.pardir))+'\\pretraindata\\OPT_results\\opt_results_rain1.npy',
                                allow_pickle=True).tolist()

In [21]:
optdata['action']

array([10,  7,  3, 10, 10,  6,  4,  5, 15,  5,  2,  4,  4,  5,  0,  4,  5,
        9, 12,  9,  7,  6,  2, 11, 10, 15, 11,  8,  7, 10,  5,  8,  8, 11,
        8,  5,  2,  5, 13,  4, 14,  7, 14,  3,  1,  3,  3,  4, 10, 11,  9,
       10,  5,  7,  8,  6,  3,  0,  3,  1, 11,  8,  0,  4,  9,  4,  2,  7,
       12, 10, 14, 10, 10, 13,  8, 11,  8,  9,  8,  8,  7,  3, 12,  2, 13,
        7,  1,  9,  3, 10, 12,  7, 13, 12,  8], dtype=int16)